SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `roles`;
DROP TABLE IF EXISTS `filieres`;
DROP TABLE IF EXISTS `utilisateurs`;
DROP TABLE IF EXISTS `memoires`;
DROP TABLE IF EXISTS `validations`;
DROP TABLE IF EXISTS `commentaires`;
DROP TABLE IF EXISTS `likes`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `rapports`;
DROP TABLE IF EXISTS `historiques`;
DROP TABLE IF EXISTS `archives`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS `roles` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `nom` VARCHAR(50) NOT NULL, `description` VARCHAR(255) DEFAULT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `uk_roles_nom` (`nom`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `roles` (`nom`, `description`) VALUES ('administrateur', 'Gestion complete'), ('directeur', 'Supervision'), ('professeur', 'Validation des memoires'), ('etudiant', 'Depot et consultation');

CREATE TABLE IF NOT EXISTS `filieres` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `nom` VARCHAR(150) NOT NULL, `code` VARCHAR(20) NOT NULL, `description` TEXT DEFAULT NULL, `statut` ENUM('active', 'inactive') DEFAULT 'active', `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `uk_filieres_code` (`code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `filieres` (`nom`, `code`, `description`, `statut`) VALUES ('Systeme Informatique et Logiciel', 'SIL', 'Formation informatique', 'active'), ('Reseaux Informatique et Telecommunication', 'RIT', 'Reseaux et telecom', 'active'), ('Systeme Industriel', 'SI', 'Electricite et automatisme', 'active'), ('Finance Comptabilite et Audit', 'FCA', 'Finance et comptabilite', 'active'), ('Banque Finance Assurance', 'BFA', 'Banque et assurance', 'active'), ('Management des Ressources Humaines', 'MRH', 'Gestion du capital humain', 'active'), ('Management Communication et Commerce', 'MCC', 'Marketing et commerce', 'active'), ('Entrepreneuriat et Gestion des Projets', 'EGP', 'Creation d entreprise', 'active'), ('Transport et Logistique', 'TL', 'Logistique et supply chain', 'active'), ('Agronomie', 'AGR', 'Production vegetale et animale', 'active'), ('Biotechnologie', 'BIO', 'Biologie appliquee', 'active'), ('Sciences Juridiques', 'SJ', 'Droit prive et public', 'active'), ('Communication et Relations Internationales', 'CRI', 'Communication et diplomatie', 'active');

CREATE TABLE IF NOT EXISTS `utilisateurs` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `role_id` INT UNSIGNED NOT NULL, `nom` VARCHAR(100) NOT NULL, `prenom` VARCHAR(100) NOT NULL, `email` VARCHAR(255) NOT NULL, `password` VARCHAR(255) NOT NULL, `telephone` VARCHAR(20) DEFAULT NULL, `avatar` VARCHAR(255) DEFAULT NULL, `niveau` VARCHAR(20) DEFAULT NULL, `statut` ENUM('actif', 'inactif', 'suspendu') DEFAULT 'actif', `derniere_connexion` TIMESTAMP NULL DEFAULT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `uk_utilisateurs_email` (`email`), KEY `idx_utilisateurs_role` (`role_id`), KEY `idx_utilisateurs_statut` (`statut`), CONSTRAINT `fk_utilisateurs_role` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `utilisateurs` (`role_id`, `nom`, `prenom`, `email`, `password`, `statut`) VALUES (1, 'Admin', 'Systeme', 'admin@uatm-gasa.cd', '$2y$10$Goi6mpH5CqW2n3PY215Eweikfy2.vL4T2N2poEO0rYL1m4zcl2HIy', 'actif');

CREATE TABLE IF NOT EXISTS `memoires` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `etudiant_id` INT UNSIGNED NOT NULL, `co_auteur_id` INT UNSIGNED DEFAULT NULL, `professeur_id` INT UNSIGNED DEFAULT NULL, `filiere_id` INT UNSIGNED NOT NULL, `titre` VARCHAR(500) NOT NULL, `description` TEXT DEFAULT NULL, `fichier_pdf` VARCHAR(255) NOT NULL, `taille_fichier` INT UNSIGNED DEFAULT NULL, `annee_academique` VARCHAR(20) NOT NULL, `type_travail` ENUM('individuel', 'binome') DEFAULT 'individuel', `statut` ENUM('brouillon', 'soumis', 'en_revision', 'valide', 'rejete', 'archive') DEFAULT 'brouillon', `date_soumission` TIMESTAMP NULL DEFAULT NULL, `date_validation` TIMESTAMP NULL DEFAULT NULL, `note_finale` DECIMAL(4,2) DEFAULT NULL, `mot_cles` VARCHAR(500) DEFAULT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_memoires_etudiant` (`etudiant_id`), KEY `idx_memoires_professeur` (`professeur_id`), KEY `idx_memoires_filiere` (`filiere_id`), KEY `idx_memoires_statut` (`statut`), KEY `idx_memoires_annee` (`annee_academique`), FULLTEXT KEY `ft_memoires_recherche` (`titre`, `description`, `mot_cles`), CONSTRAINT `fk_memoires_etudiant` FOREIGN KEY (`etudiant_id`) REFERENCES `utilisateurs` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT `fk_memoires_professeur` FOREIGN KEY (`professeur_id`) REFERENCES `utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT `fk_memoires_filiere` FOREIGN KEY (`filiere_id`) REFERENCES `filieres` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `validations` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `memoire_id` INT UNSIGNED NOT NULL, `validateur_id` INT UNSIGNED NOT NULL, `decision` ENUM('en_attente', 'approuve', 'rejete', 'revision') DEFAULT 'en_attente', `commentaire` TEXT DEFAULT NULL, `note` DECIMAL(4,2) DEFAULT NULL, `date_validation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_validations_memoire` (`memoire_id`), KEY `idx_validations_validateur` (`validateur_id`), CONSTRAINT `fk_validations_memoire` FOREIGN KEY (`memoire_id`) REFERENCES `memoires` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `fk_validations_validateur` FOREIGN KEY (`validateur_id`) REFERENCES `utilisateurs` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `commentaires` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `memoire_id` INT UNSIGNED NOT NULL, `auteur_id` INT UNSIGNED NOT NULL, `contenu` TEXT NOT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_commentaires_memoire` (`memoire_id`), KEY `idx_commentaires_auteur` (`auteur_id`), CONSTRAINT `fk_commentaires_memoire` FOREIGN KEY (`memoire_id`) REFERENCES `memoires` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `fk_commentaires_auteur` FOREIGN KEY (`auteur_id`) REFERENCES `utilisateurs` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `likes` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `memoire_id` INT UNSIGNED NOT NULL, `utilisateur_id` INT UNSIGNED NOT NULL, `type` ENUM('like', 'dislike') DEFAULT 'like', `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `uk_likes_unique` (`memoire_id`, `utilisateur_id`), KEY `idx_likes_utilisateur` (`utilisateur_id`), CONSTRAINT `fk_likes_memoire` FOREIGN KEY (`memoire_id`) REFERENCES `memoires` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `fk_likes_utilisateur` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateurs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notifications` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `utilisateur_id` INT UNSIGNED NOT NULL, `titre` VARCHAR(255) NOT NULL, `message` TEXT NOT NULL, `type` ENUM('info', 'success', 'warning', 'error') DEFAULT 'info', `lu` TINYINT(1) DEFAULT 0, `lien` VARCHAR(255) DEFAULT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_notifications_utilisateur` (`utilisateur_id`), KEY `idx_notifications_lu` (`lu`), CONSTRAINT `fk_notifications_utilisateur` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateurs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rapports` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `titre` VARCHAR(255) NOT NULL, `type_rapport` ENUM('statistiques', 'validation', 'activite', 'general') NOT NULL, `auteur_id` INT UNSIGNED NOT NULL, `contenu` TEXT DEFAULT NULL, `date_debut` DATE DEFAULT NULL, `date_fin` DATE DEFAULT NULL, `fichier` VARCHAR(255) DEFAULT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_rapports_auteur` (`auteur_id`), KEY `idx_rapports_type` (`type_rapport`), CONSTRAINT `fk_rapports_auteur` FOREIGN KEY (`auteur_id`) REFERENCES `utilisateurs` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `historiques` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `utilisateur_id` INT UNSIGNED NOT NULL, `action` VARCHAR(100) NOT NULL, `entite` VARCHAR(50) NOT NULL, `entite_id` INT UNSIGNED DEFAULT NULL, `details` TEXT DEFAULT NULL, `ip_address` VARCHAR(45) DEFAULT NULL, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_historiques_utilisateur` (`utilisateur_id`), KEY `idx_historiques_entite` (`entite`, `entite_id`), KEY `idx_historiques_date` (`created_at`), CONSTRAINT `fk_historiques_utilisateur` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateurs` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `archives` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `memoire_id` INT UNSIGNED NOT NULL, `archive_par` INT UNSIGNED NOT NULL, `raison` TEXT DEFAULT NULL, `date_archivage` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `statut` ENUM('archive', 'restaure') DEFAULT 'archive', PRIMARY KEY (`id`), KEY `idx_archives_memoire` (`memoire_id`), KEY `idx_archives_archive_par` (`archive_par`), CONSTRAINT `fk_archives_memoire` FOREIGN KEY (`memoire_id`) REFERENCES `memoires` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `fk_archives_archive_par` FOREIGN KEY (`archive_par`) REFERENCES `utilisateurs` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;